export async function addCoverPage(
  pdf,
  story
) {
  //---------------------------------------
  // Background
  //---------------------------------------

  pdf.setFillColor(
    255,
    240,
    246
  );

  pdf.rect(
    0,
    0,
    210,
    297,
    "F"
  );

  //---------------------------------------
  // Logo
  //---------------------------------------

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.setFontSize(38);

  pdf.text(
    "❤️",
    105,
    45,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Title
  //---------------------------------------

  pdf.setFontSize(28);

  pdf.text(
    "MOMENTRY",
    105,
    70,
    {
      align: "center",
    }
  );

  pdf.setFontSize(18);

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.text(
    "Our Story",
    105,
    82,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Couple
  //---------------------------------------

  const partner =
    story?.partner_name ||
    "Partner";

  const owner =
    story?.owner_name ||
    "You";

  pdf.setFontSize(22);

  pdf.text(
    `${owner} ❤️ ${partner}`,
    105,
    120,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Dates — prefer the real anniversary
  // (stories.anniversary_date) over a
  // placeholder.
  //---------------------------------------

  const start =
    story?.anniversary_date ||
    story?.relationship_start
      ? new Date(
          story.anniversary_date ||
            story.relationship_start
        ).toLocaleDateString()
      : "-";

  const startLabel =
    story?.anniversary_date ||
    story?.relationship_start
      ? "Together since"
      : "";

  const today =
    new Date().toLocaleDateString();

  pdf.setFontSize(15);

  if (startLabel) {
    pdf.setFont("helvetica", "italic");

    pdf.setFontSize(11);

    pdf.setTextColor(140);

    pdf.text(startLabel, 105, 144, {
      align: "center",
    });

    pdf.setTextColor(0);

    pdf.setFont("helvetica", "normal");
  }

  pdf.setFontSize(15);

  pdf.text(
    `${start}`,
    105,
    150,
    {
      align: "center",
    }
  );

  pdf.text(
    "↓",
    105,
    158,
    {
      align: "center",
    }
  );

  pdf.text(
    today,
    105,
    166,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Quote
  //---------------------------------------

  pdf.setFontSize(18);

  pdf.setFont(
    "times",
    "italic"
  );

  pdf.text(
    "Every memory tells",
    105,
    220,
    {
      align: "center",
    }
  );

  pdf.text(
    "a beautiful story.",
    105,
    230,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Cover photo — full-bleed behind a
  // translucent scrim when the story has
  // one.
  //---------------------------------------

  if (story?.cover_photo) {
    try {
      const { imageToBase64 } = await import(
        "./imageUtils"
      );

      const image = await imageToBase64(
        story.cover_photo
      );

      if (image) {
        pdf.setFillColor(255, 240, 246);

        pdf.rect(0, 180, 210, 90, "F");

        pdf.addImage(
          image,
          "JPEG",
          55,
          180,
          100,
          75
        );
      }
    } catch {
      // Decorative — ignore failures.
    }
  }

  //---------------------------------------
  // Footer
  //---------------------------------------

  pdf.setFontSize(11);

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.text(
    "Generated by Momentry",
    105,
    280,
    {
      align: "center",
    }
  );
}