export async function addCoverPage(
  pdf,
  story
) {
  //---------------------------------------
  // Background
  //---------------------------------------

  pdf.setFillColor(
    255,
    240,
    246
  );

  pdf.rect(
    0,
    0,
    210,
    297,
    "F"
  );

  //---------------------------------------
  // Logo
  //---------------------------------------

  pdf.setFont(
    "helvetica",
    "bold"
  );

  pdf.setFontSize(38);

  pdf.text(
    "❤️",
    105,
    45,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Title
  //---------------------------------------

  pdf.setFontSize(28);

  pdf.text(
    "MOMENTRY",
    105,
    70,
    {
      align: "center",
    }
  );

  pdf.setFontSize(18);

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.text(
    "Our Story",
    105,
    82,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Couple
  //---------------------------------------

  const partner =
    story?.partner_name ||
    "Partner";

  const owner =
    story?.owner_name ||
    "You";

  pdf.setFontSize(22);

  pdf.text(
    `${owner} ❤️ ${partner}`,
    105,
    120,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Dates
  //---------------------------------------

  const start =
    story?.relationship_start
      ? new Date(
          story.relationship_start
        ).toLocaleDateString()
      : "-";

  const today =
    new Date().toLocaleDateString();

  pdf.setFontSize(15);

  pdf.text(
    `${start}`,
    105,
    150,
    {
      align: "center",
    }
  );

  pdf.text(
    "↓",
    105,
    158,
    {
      align: "center",
    }
  );

  pdf.text(
    today,
    105,
    166,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Quote
  //---------------------------------------

  pdf.setFontSize(18);

  pdf.setFont(
    "times",
    "italic"
  );

  pdf.text(
    "Every memory tells",
    105,
    220,
    {
      align: "center",
    }
  );

  pdf.text(
    "a beautiful story.",
    105,
    230,
    {
      align: "center",
    }
  );

  //---------------------------------------
  // Footer
  //---------------------------------------

  pdf.setFontSize(11);

  pdf.setFont(
    "helvetica",
    "normal"
  );

  pdf.text(
    "Generated by Momentry",
    105,
    280,
    {
      align: "center",
    }
  );
}